version: 2.1
orbs:
  docker: circleci/docker@1.0.0
jobs:
  build-and-push:
    executor: docker/docker
    resource_class: small
    steps:
      - run: |
          echo "$CIRCLE_TAG"
          echo "$CIRCLE_SHA1"
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKER_ORG/$DOCKER_REPO
          tag: "$CIRCLE_SHA1,$CIRCLE_TAG,latest"
      - docker/push:
          image: $DOCKER_ORG/$DOCKER_REPO
          tag: "$CIRCLE_SHA1,$CIRCLE_TAG,latest"

workflows:
  version: 2
  commit:
    jobs:
      - build-and-push:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
